// Code generated by "stringer -linecomment -type=UpdateType"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UpdateMessage-0]
	_ = x[UpdateEditedMessage-1]
	_ = x[UpdateChannelPost-2]
	_ = x[UpdateEditedChannelPost-3]
	_ = x[UpdateInlineQuery-4]
	_ = x[UpdateChosenInlineResult-5]
	_ = x[UpdateCallbackQuery-6]
	_ = x[UpdateShippingQuery-7]
	_ = x[UpdatePreCheckoutQuery-8]
	_ = x[UpdatePoll-9]
	_ = x[UpdatePollAnswer-10]
	_ = x[UpdateMyChatMember-11]
	_ = x[UpdateChatMember-12]
	_ = x[UpdateChatJoinRequest-13]
}

const _UpdateType_name = "messageedited_messagechannel_postedited_channel_postinline_querychosen_inline_resultcallback_queryshipping_querypre_checkout_querypollpoll_answermy_chat_memberchat_memberchat_join_request"

var _UpdateType_index = [...]uint8{0, 7, 21, 33, 52, 64, 84, 98, 112, 130, 134, 145, 159, 170, 187}

func (i UpdateType) String() string {
	if i < 0 || i >= UpdateType(len(_UpdateType_index)-1) {
		return "UpdateType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UpdateType_name[_UpdateType_index[i]:_UpdateType_index[i+1]]
}
